### ISSUE TITLE
Memory leak during project switching

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#282] opened 2014-12-30 12:30 UTC
The memory start leaking during the project switching, rendering the app unresponsive until I kill it. This may be related to #279 
Need to go through the project switching code carefully to ensure it is reliable. Stress test using several projects of significant size.

**Comment by damithc** [comment] 2015-01-03 04:08
Didn't encounter this bug for a while, but happened once today.

**Comment by taychunmei** [comment] 2015-01-03 04:32
Okay, I'm trying to find the source of this bug

**Comment by damithc** [comment] 2015-01-05 01:56
Looks like project switching is not the only cause. When I leave HT open overnight, I have to kill HT in the morning because it is already frozen due to a memory leak during the night. Happened twice.

**Comment by taychunmei** [comment] 2015-01-05 10:07
Pushed a fix for memory leak when project is opened.
There is still a memory leakage when switching project though

**Comment by damithc** [comment] 2015-01-07 01:08
Happened again during the night. Seems leaving it running overnight is a reliable way to reproduce the leak.

**Comment by damithc** [comment] 2015-01-09 01:53
Happened once again when I left it running overnight. This time the flood of refreshes happened just as I resumed work today morning, not during the night. Otherwise the log is similar to last time.
Here's the relevant part:
```
8638366 08 Jan 2015 21:46:38 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
8696992 08 Jan 2015 21:47:36 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
8696992 08 Jan 2015 21:47:36 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
8756992 08 Jan 2015 21:48:36 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
8756992 08 Jan 2015 21:48:36 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
8817005 08 Jan 2015 21:49:36 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
8817006 08 Jan 2015 21:49:36 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
51833708 09 Jan 2015 09:46:33 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
51833713 09 Jan 2015 09:46:33 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
51833716 09 Jan 2015 09:46:33 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
51833734 09 Jan 2015 09:46:33 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
51833736 09 Jan 2015 09:46:33 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
51833737 09 Jan 2015 09:46:33 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
51833740 09 Jan 2015 09:46:33 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
51833740 09 Jan 2015 09:46:33 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
51833742 09 Jan 2015 09:46:33 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
51833743 09 Jan 2015 09:46:33 INFO UI [Timer-30] - Triggered event RefreshDoneEvent
51833745 09 Jan 2015 09:46:33 INFO UI [Timer-30] - About to trigger event RefreshDoneEvent
```

**Comment by taychunmei** [comment] 2015-01-09 08:15
For the flood refresh, I've replaced timers with scheduled executor #343 & pr: #344. I think it may stop the leak issue not caused by project switching

**Comment by damithc** [comment] 2015-01-09 08:18
Any clue about the memory leak during project switching? Now that we have
more logging, have you tried reproducing the leak and examining the logs?

**Comment by damithc** [comment] 2015-01-11 01:31
Happened again when left running overnight. This was a different computer. The comp was in sleep mode and the flood happened at the point of waking up.

**Comment by taychunmei** [comment] 2015-01-12 02:37
Hi, noted about the project switching. I will look into it
Did both computers experienced the flooding?

**Comment by damithc** [comment] 2015-01-12 02:54
Flooding overnight? yes, both computers. Although it doesn't happen every
day. Try to do a few sleep-wakeup while HT is running to see if you can
reproduce it.
During project switching: only one computer. It happened when I was trying
to switch from a big project to another.

**Comment by damithc** [comment] 2015-02-06 01:02
Haven't seen this for a couple of weeks now

**Comment by dariusf** [comment] 2015-02-06 03:15
What's the maximum that memory usage climbs to now?

This was probably resolved with the removal of the observables and listeners.

**Comment by damithc** [comment] 2015-02-06 03:26
Interestingly, it depends on the computer. For my desktop it's usually about 250Mb and for the laptop it is about 400Mb, but it is stable in both cases.

**Closed** 2015-02-11 07:54 UTC
Labels: aspect-sync, priority.high, status.accepted, type.bug
