### ISSUE TITLE
closed issues shown under state:open filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#281] opened 2014-12-30 12:15 UTC
V0.20

![image](https://cloud.githubusercontent.com/assets/1673303/5578355/81d73202-9060-11e4-87b1-507df8626898.png)

**Comment by damithc** [comment] 2015-01-02 11:24
This one is a show-stopper. Please fix quickly.

**Comment by taychunmei** [comment] 2015-01-03 02:46
I'll look into it now

**Comment by taychunmei** [comment] 2015-01-03 03:07
Right now I'm not able to replicate it. 
I have a column with "state:open". Close HT -> close some issues on github -> open HT -> issue is gone from column.

Maybe you can share with me your steps?

**Comment by damithc** [comment] 2015-01-03 04:00
closing (to test issue)

**Comment by damithc** [comment] 2015-01-03 04:07
I can't replicate it either. It may be related to how old the change is. e.g. close HT, close an issue, open HT after *one day*
When you refresh a project at startup/switch, make sure you get all updates since the last recorded refresh by HT. Is that what you do now?
Anyway, I'll leave this closed for now.

**Comment by taychunmei** [comment] 2015-01-03 04:31
Yes, a lastcheckedtime is being saved for each repo, so it'll get any new updates from that time.

**Comment by damithc** [comment] 2015-01-03 05:28
Noticed another case of this on TEAMMATES project. Not sure how it happened though.

**Comment by damithc** [comment] 2015-01-03 05:40
This update happened during last night. I had HT open (not sure which project was open) but I found it suffering from memory leak and had to kill it (from task manager) today morning. Not sure if that is related to this problem. Perhaps the last checked date was written but issues were not updated? By the way, do you update the json file at exit or after every refresh?
![image](https://cloud.githubusercontent.com/assets/1673303/5601700/945a421c-934d-11e4-994a-b5f319daa1af.png)

**Comment by taychunmei** [comment] 2015-01-04 02:45
The json file is updated after every refresh.

I suspected that this issue could have been caused by a timeout (since it's not being checked before the last checked date gets written) but I wasn't able to replicate the issue though with the network error. Thanks for providing an alternative explanation!

**Comment by damithc** [comment] 2015-01-04 02:57
If cannot pinpoint the cause, may be do #299 first? It can help in this
issue too.

**Comment by damithc** [comment] 2015-01-05 03:31
I have a case where a merged PR appears under `status:open` even after resetting the cache (deleted the json file).

**Comment by damithc** [comment] 2015-01-05 03:34
It's the same PR 2778 in the previous screenshot from TEAMMATES

**Comment by damithc** [comment] 2015-01-05 03:37
Ignore the previous observation. I deleted the wrong json file in that instance. The issue is shown correctly after a proper 'reset' of cache. Sorry.

**Comment by taychunmei** [comment] 2015-01-05 07:53
I've pushed a fix (by writing to cache only if there are any changes instead of every refresh) which hopefully solves this problem. Do let me know if it occurs again

**Comment by taychunmei** [comment] 2015-01-05 08:08
Just encountered this bug myself. I managed to reproduce it once. Will try again

**Closed** 2015-01-05 10:00 UTC
Labels: aspect-sync, priority.urgent, status.accepted, type.bug
