### ISSUE TITLE
unexpected default project at start up

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#665] opened 2015-06-01 23:43 UTC
At times, the default project at start up doesn't seem to be the one I had selected when I shut down HT the previous time.

**Comment by damithc** [comment] 2015-06-17 14:05
Confirmed, happened a few more times.

**Comment by HyungJon** [comment] 2015-06-18 06:45
I suspect this has something to do with method addToLastViewedRepositories in GlobalConfig. The sorting to be specific.

**Comment by HyungJon** [comment] 2015-06-19 01:42
Does

lastViewedRepositories.stream()
                .map(RepoViewRecord::getRepository)
                .collect(Collectors.toList());

(GlobalConfig, line 113) return the List in the same order as the original? Because in addToLastViewedRepositories, if there are more than 10 repositories viewed, then after sorting the repositories are removed starting from the last item. Then in Preferences.getLastViewedRepository (line 92), what this method returns is also the last item in the List. So we might be either removing the repos starting from the most recent, or retrieving the first item in the list. However I'm not familiar with the above code so I can't be sure.

**Comment by acruis** [comment] 2015-06-22 09:22
@HyungJon Are you still working on this issue?

**Comment by HyungJon** [comment] 2015-06-22 09:31
Yes, though I don't have much progress besides finding out that removing the first repo in record instead of the last one doesn't solve the problem. I intend to try some bigger changes that might work.

**Comment by HyungJon** [comment] 2015-06-22 09:34
The issue may not be in the records, but rather in recognizing that the user selected another repo.

**Comment by acruis** [comment] 2015-06-22 09:46
Currently whenever an `openRepository` is called from `logic`, the newly opened repo will be added to the list of `lastViewedRepositories`, without the default repo being changed in the repository selector. I think that is why the default repository changes on the next launch if you open a new repository.

In fact, I don't see a need to keep a list of `lastViewedRepositories` when all we use it for, currently, is to find out the default repository. What are the bigger changes that you're thinking of?

**Comment by HyungJon** [comment] 2015-06-22 10:17
As I understand it, default repo is set only at startup after logging in. It's used for the browser component I think, and all other parts (e.g. login dialog) refer to lastViewedRepositories.

When the login dialog retrieves a wrong repo, it's probably because 1) the list is correct, but wrong item is retrieved or 2) the list is built in a wrong way or 3) the list isn't being built at all. Through testing I've mostly confirmed that 2 is not the case though. I suspect 3: sometimes logic fails to add a repo to the list when the repo is opened.

I agree keeping a list might be redundant as it currently is, though it could be used for completing the drop-down list for the repositories in the future.

**Comment by HyungJon** [comment] 2015-06-22 13:23
I believe I found the source of this problem. From reading the logs I noticed Logic.openRepository was being invoked only when the repo to open is typed in manually, and not when the repo is selected from the drop-down list. The default repo at startup is probably the last repo to be manually typed in during the last session. Hence the default repo not matching the last seen repo.

I'll now start working on making it so that a repo is added to list of viewed repos when selected from drop-down.

**Comment by HyungJon** [comment] 2015-06-24 03:55
I may require assistance with the JavaFX functions used in RepositorySelector. Specifically, I need to know how line 15 works. I understood that this line is what triggers ui.primaryRepoChanged when something is typed into the combo box, and I'm trying to extend the event to include something being selected from the combo box. I've been trying to search information on this, but I'm afraid this type of event handling (using event and callback) is completely new to me.

An alternative approach would be to invoke openRepository using the function that displays the repo selected from the combobox, though I doubt the code is going to look clean then.

**Comment by acruis** [comment] 2015-06-24 06:25
Currently `ui.primaryRepoChanged` already triggers both when something is typed into the combo box as well as when something is selected from the combo box. Insert a `System.out.println` statement within the code of `ui.primaryRepoChanged` and you'll see that the print statement is executed both when the user presses <kbd>Enter</kbd> as well as when the user selects from the combo box.

As for how the event registration is done, the code specified by `onValueChangeCallback` will run whenever the `valueProperty` of the combo box is modified (which is when <kbd>Enter</kbd> is pressed or when an item is selected) as we register a listener for this property in [line 36](https://github.com/HubTurbo/HubTurbo/blob/d10c9d912e2a6379daf257e078f7ac4c501d11d8/src/main/java/ui/RepositorySelector.java#L36).

As you can see from line 15, upon initialisation of a `RepositorySelector`, the callback is `e -> {}`. Nothing is inside the bracket, which means that nothing gets executed. This is the default callback to use, but after we initialise the `RepositorySelector` in [line 404 of UI.java](https://github.com/HubTurbo/HubTurbo/blob/d10c9d912e2a6379daf257e078f7ac4c501d11d8/src/main/java/ui/UI.java#L404), we immediately set the callback to be the function `primaryRepoChanged` in line 405. Thus, whenever the `valueProperty` of the combo box is modified (which is, again, when <kbd>Enter</kbd> is pressed or when an item is selected), the function `primaryRepoChanged` in `UI.java` will be called.

**Comment by HyungJon** [comment] 2015-06-24 07:38
If UI.primaryRepoChanged does trigger properly but the repo still isn't added to the list, then it must mean something is wrong with the IF statements in Logic.openRepository.

**Comment by HyungJon** [comment] 2015-06-24 07:40
![cap 2015-06-24 15-39-20-647](https://cloud.githubusercontent.com/assets/8623463/8324887/3c684024-1a87-11e5-9f38-54d355bcf9c0.png)
Cause of the issue found. It should not be checking whether the selected repo is open, but whether it's currently the primary repo.

**Comment by lejolly** [comment] 2015-07-03 05:23
Closed via #749.

**Closed by lejolly** 2015-07-03 05:23 UTC
Labels: priority.medium, type.bug
