### ISSUE TITLE
Change label option available without correct permissions

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/HubTurbo#1414] opened 2016-03-25 10:12 UTC
The leftmost panel works fine; it does not allow users to change labels on issues if they don't have permission.

Every other panel has that issue.

**Comment by m133225** [comment] 2016-03-25 10:29
I can't seem to reproduce this. All the panels give a write error if I don't have permission. Any specific steps?

**Comment by YijinL** [comment] 2016-03-25 10:38
I mean the first panel does not even have the `Change labels (L)` option in the dropdown when right clicking an issue card, but other panels show that option.

**Comment by m133225** [comment] 2016-03-25 10:43
I think this is a bug with the context menu instead, as noted in #1383. The change labels option is not supposed to hide even when the user doesn't have permission. Maybe hiding the option could be an additional feature instead?

**Comment by damithc** [comment] 2016-03-25 11:37
Yes, at the moment we don't have functionality to hide actions when the user does not have permission to perform it. The problem here is caused by a different bug. In future we can add a feature to disable (not hide) functions the user is not permitted to perform.

**Comment by damithc** [comment] 2016-03-25 11:38
Closing because this is a duplicate.

**Closed by damithc** 2016-03-25 11:38 UTC
