### ISSUE TITLE
feed panels: aggregate label changes done close together

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#498] opened 2015-03-07 14:41 UTC
See screenshot. It's better if we can aggregate label changes like the Web UI does.
![image](https://cloud.githubusercontent.com/assets/1673303/6541706/c7b4bd00-c51a-11e4-84ce-189c5e94a6e0.png)

**Comment by dariusf** [comment] 2015-08-19 15:43
Duplicate of #744.

**Closed by dariusf** 2015-08-19 15:43 UTC
Labels: feature-feed, priority.medium, type.enhancement
