### ISSUE TITLE
Error not showing when action has failed

### ISSUE THREAD

**Issue by m133225** [HubTurbo/HubTurbo#1257] opened 2016-02-15 15:13 UTC
I tried to change a label from `type.story` to `type.bug` on HubTurbo/HubTurbo (while trying to fix #1237) which I didn't have write permissions on, and was not prompted with an error. Instead, it was deemed as 'successful' by HubTurbo. This bug should have been introduced quite recently since it was still working when #1237 was created.
![screen shot 2016-02-15 at 11 03 25 pm](https://cloud.githubusercontent.com/assets/12193772/13052182/68f2a0e2-d438-11e5-9b1f-34876d5c57d9.png)

**Comment by ndt93** [comment] 2016-02-15 15:17
See #1246 and #1250.

The reason is `RepoOpControl.deque()` swallows exception when invoking `.get()`

**Comment by damithc** [comment] 2016-02-15 15:22
Can close if this is a duplicate of #1246

**Closed** 2016-02-15 15:22 UTC
