### ISSUE TITLE
Don't load issue in bView if deselected within a short time

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#327] opened 2015-01-07 07:26 UTC
Currently, users need to press shift to avoid loading in bView.
We can make HT smarter: don't load in bView if the selection moves out within a short period (user is probably just passing through the issue). The downside is, we have to delay loading the issue slightly. This is similar to Gmail delaying the 'send' operation so that the user has a short window to undo the send.

**Comment by damithc** [comment] 2015-01-08 09:12
Another solution is to load the latest url in the queue only (instead of loading all in sequence).

**Comment by rd1992** [comment] 2015-03-25 10:00
duplicate of #490

**Closed by rd1992** 2015-03-25 10:00 UTC
Labels: aspect-ui, feature-browser, priority.low, status.accepted, type.enhancement
