### ISSUE TITLE
Unread updates appearing as read

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#939] opened 2015-09-06 01:41 UTC
This appears as read although it was updated in the last 9 hours and I did not use HT during that 9 hours. I noticed it for two HT issues so far.
![image](https://cloud.githubusercontent.com/assets/1673303/9701984/436e9318-547b-11e5-81a8-aba1595c0f0d.png)

**Comment by damithc** [comment] 2015-09-08 23:36
This is happening a lot. Need to fix by next release.

**Comment by ndt93** [comment] 2015-09-09 04:47
@damithc Is the behavior of this problem like this:

* Scenario 1: User marked an issue as read -> User closed HubTurbo -> There are some updates on that issue -> User opens HubTurbo again -> That issue is stilled marked as read.
* Scenario 2: User marked an issue as read -> There are some updates on that issue -> Issue is marked as unread in the UI -> User closes HubTurbo -> User opens HubTurbo again -> That issue is still marked as read

**Comment by damithc** [comment] 2015-09-09 05:40
I have no definite proof, but I think it's scenario 1. If scenario 2 happened, I never noticed it.

**Comment by ndt93** [comment] 2015-09-09 06:23
I can reproduce both scenarios now. The problem is that when a new/updated issue is loaded, its *read state* is determined by the *presence* of `markReadAt` time (stored in *Preference*) but not by comparing with the issue's `updatedTime`. Then when an update for that issue come in, another field called `isCurrentlyRead` is set to `false` but its `markReadAt` entry is not cleared in the *Preference*, relying on the assumption that `markReadAt` time can be used to determined its *read state* next time.

So we can do either or both of these to solve this: clear `markReadAt` time entry for the issue in the *Preference* or check `markAsReadAt` against `updatedTime`.

Another point is that there are two fields in TurboIssue with regards to *read state*: `isCurrentlyRead` and `markedReadAt`, both are strongly correlated to each other but have independent get/set and are used separately in various places. This leads to quite a number of inconsistencies. Should we refactor this? (either hide them in a unifying interface in `TurboIssue` or just use `markedReadAt` time to determine `isCurrentlyRead`)

**Comment by damithc** [comment] 2015-09-09 06:27
Good job @ndt93 on reproducing and figuring out the cause.
Others any comment on the suggested solution?

**Comment by ndt93** [comment] 2015-09-09 14:31
So we agreed to check `markReadAt` against `updatedAt` to determine the read state, and get rid of the `isCurrentlyRead` field. If anyone recalls why we need 2 fields in the first place, please report here so we can avoid potential regression.

**Closed** 2015-09-12 02:37 UTC
Labels: feature-feed, priority.urgent, type.bug
