### ISSUE TITLE
Double space is added to filter before changing focus to the issue list

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#564] opened 2015-03-29 03:44 UTC
Usually this is not a problem, unless the insertion point is in the middle of the filter
![image](https://cloud.githubusercontent.com/assets/1673303/6884025/e7222f20-d608-11e4-9028-84c5ebb40c7c.png)

**Comment by lejolly** [comment] 2015-08-25 04:03
Duplicate of #897.

**Closed by lejolly** 2015-08-25 04:03 UTC
Labels: priority.low, type.bug
