### ISSUE TITLE
Focus not transferred to bView when needed

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#927] opened 2015-09-02 07:09 UTC
e.g. When pressing 'M', the focus is supposed to transfer to bView, but it doesn't

**Comment by damithc** [comment] 2015-09-03 10:03
Can fix soon? This thing is irritating.

**Comment by rd1992** [comment] 2015-09-03 10:26
Will fix tonight

**Comment by rd1992** [comment] 2015-09-03 18:33
Error is because the handle to the pview is always null. @damithc can you confirm what window has focus on startup of the application? I have bview in focus

**Comment by damithc** [comment] 2015-09-04 01:37
I see. Waiting for the fix.

**Comment by rd1992** [comment] 2015-09-04 04:27
@damithc could you try f49d3b8cacfcabc8cef8ef55c77b121d897e8241 ? i haven't submitted a PR yet as i am still testing if this can break under any circumstance. The problem is that with the new chromedriver they have made the window to be closer to the actual chrome window, but this also makes it harder for us to identify which is the selenium chrome window. i am testing it now and if you see that it stops working please comment here and let me know

**Comment by damithc** [comment] 2015-09-04 04:42
Seems to work so far. Perhaps we can load a dummy page first (e.g. a static
splash screen page from our website) and identify the window based on that?

**Comment by rd1992** [comment] 2015-09-04 04:45
Yes. actually we could create a github page over at [pages] (https://pages.github.com/) . and then go to the actual login page.

**Comment by damithc** [comment] 2015-09-04 04:52
That's one option. Another option is to put up a simple html page in our
SoC unix account. Can be used for tracking usage stats too.

**Comment by damithc** [comment] 2015-09-04 12:05
Just noticed that when I press `R`, the cursor goes to both the address bar of the bView and the comment box. It doesn't happen all the time, but it is frequent enough to be noticeable.

**Comment by damithc** [comment] 2015-09-04 12:10
Another thing, the problem mention in the previous comment happens only after starting HT and reproducible (start HT, click on an issue, and type `R`). Once I have typed one comment in the bView, it doesn't happen any more.

**Comment by damithc** [comment] 2015-09-05 01:47
Above problem (cursor in address bar) confirmed using my other comp too.

**Comment by rd1992** [comment] 2015-09-05 15:47
I tried this and yes this is reproducible. And not only for R. Even does for A.

**Comment by rd1992** [comment] 2015-09-05 16:43
Well i tried with 2.19 also. Even tried a JS only solution. This seems like a regression. I have opened an issue over at Chromedriver issues (https://code.google.com/p/chromedriver/issues/list). The only workaround right now is to switch back to the previous chromedriver version.

**Comment by damithc** [comment] 2015-09-06 01:33
@lejolly any problem with going back to previous version of chrome driver?
@rd1992 can you give the link to the issue you filed here? Keep us updated about its progress.

**Comment by lejolly** [comment] 2015-09-06 16:46
No problems, it just might not work with later versions of chrome (I think it stopped working with v46 of chrome).

**Comment by rd1992** [comment] 2015-09-07 19:34
On further testing and talking to chromedriver devs, realized that this has nothing to do with chromedriver version. This is because of us using a custom chrome profile( added in 080d282e4504dc04f3d7399d04b98e813cf56fff)
Specifically this is causing the issue : https://github.com/HubTurbo/HubTurbo/blob/080d282e4504dc04f3d7399d04b98e813cf56fff/src/main/java/browserview/BrowserComponent.java#L163

Anyway the bug report was filed [here] (https://code.google.com/p/chromedriver/issues/detail?id=1214)

**Comment by damithc** [comment] 2015-09-08 00:10
What's the proposed solution? 
@HansNewbie FYI.

**Comment by rd1992** [comment] 2015-09-08 01:21
Well there is a 2 part solution. 
First is we disable 2FA for now and go through the login page everytime (like we used to).
We bring back 2FA when the chromedriver devs reply to the issue filed.

**Comment by HansNewbie** [comment] 2015-09-08 01:35
I am yet to test this, but the problem might be because without user profile, we always crawl the login page in which the focus will be on the webpage upon starting HubTurbo. On using user profile, although the chromedriver loads github mainpage, the webpage is never crawled, hence the focus is not on the webpage.

**Comment by damithc** [comment] 2015-09-08 02:06
Do a fake crawl as a dirty fix? :-)

**Comment by HansNewbie** [comment] 2015-09-08 02:08
I am trying to do a fake crawl and see what happens. Will report soon.

**Comment by HansNewbie** [comment] 2015-09-08 02:18
@damithc apparently crawling does not remove the focus from the address bar. I think it's driver issue. I will try if I can find a solution.

**Comment by HansNewbie** [comment] 2015-09-08 02:36
@damithc I don't think there is any possible fix right now. The focus on the address bar cannot be removed at all.

@rd1992 might be related to https://code.google.com/p/chromedriver/issues/detail?id=762

**Comment by damithc** [comment] 2015-09-08 02:48
Comment 24 says they managed to solve it using TAB.

**Comment by HansNewbie** [comment] 2015-09-08 02:55
@damithc if we want to do that, we need to introduce `org.loadui.testfx.GuiTest` or other key press simulator since pressing the tab must occur outside of the webpage. Using `sendKeysToBrowser("\t")` (should be KeyCode.TAB but did that just to try out) will not work because we are pressing tab inside the html body. Such key press must be at chromedriver level.

**Comment by damithc** [comment] 2015-09-08 02:58
Rolling back to previous driver solves this? Or undoing the 2FA support solves this? One of the two must work because we did not have this problem before.

**Comment by HansNewbie** [comment] 2015-09-08 03:08
Undoing 2FA support solves this focus to address bar.

Quick question: when I press `R`, I get to the comment box but the keyboard control is still on the webpage (instead of I can start typing right away). Is it because I am on Mac? This happens even when I rolled back to previous driver.
That being said, 2FA support will keep address bar highlighted which is the current problem.

**Comment by damithc** [comment] 2015-09-08 03:28
The original problem was keyboard control remaining in pView. The cursor going to address bar was a subsequent problem discovered (or caused) during this fix.

**Comment by HansNewbie** [comment] 2015-09-08 03:35
Then yes, I can verify the address bar problem is due to 2FA support.

**Comment by rd1992** [comment] 2015-09-10 13:04
Closed via 81032ce25a694c880c98f711b9ceceaed01668cb

**Closed by rd1992** 2015-09-10 13:04 UTC
Labels: aspect-navigation, feature-browser, priority.urgent, type.bug
