### ISSUE TITLE
New milestones cannot be used in filters unless the cache is refreshed

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#906] opened 2015-08-27 01:31 UTC
It happened again. 
`milestone:V5.51` does not capture issues assigned to it unless I refresh the cache. Note that the milestone V5.51 was created after the previous refresh of cache.

**Comment by damithc** [comment] 2015-08-27 01:35
Although I can't reproduce the same problem for HT issues.

**Comment by damithc** [comment] 2015-08-29 07:00
Can anybody else reproduce this for `repo:teammates/repo milestone:V5.51` ?

**Comment by ndt93** [comment] 2015-08-29 07:42
Yup, I was looking into this and my cache doesn't have the milestone either. The milestones' etag has been updated to after the new milestone is created but from the log, the new milestone has not been downloaded at all (or at least not merged into the new list of milestones that are shown in the log).

I'm unable to reproduce this on hubturbo or my own test repo so might not have enough time to dig up the problem by the next milestone. Maybe we can prepare some logging/breakpoints first before the next teammate is created to see what happen.

**Comment by dariusf** [comment] 2015-08-29 16:51
I'm also trying to reproduce but haven't been able to yet. So that particular milestone just doesn't appear? Any other missing milestones or resources?

**Comment by ndt93** [comment] 2015-08-29 17:42
Just the V5.51. I removed the milestones' etag in the cache and then whole thing could be downloaded properly again.

**Comment by dariusf** [comment] 2015-08-30 04:15
When an error occurs with either the initial download or subsequent updates, store/ETags aren't supposed to be saved (it defaults to the empty model with the empty update signature). Maybe there's a bug with this, and it's somehow saving even on error?

**Comment by ndt93** [comment] 2015-08-30 08:19
I suppose it's not due to an apparent download exception. Here is the update part from the log

* 810404 25 Aug 2015 18:12:36 INFO UpdateService [pool-4-thread-2] - New ETag for teammates/repo/milestones: Optional[b2d8515935b063fac31d9494a2f0475f]
* 810406 25 Aug 2015 18:12:36 INFO UpdateMilestonesTask [pool-4-thread-2] - teammates/repo | 171 milestone(s)) changed: [V1.0, V2.0, V3.0, V4.1,V4.2, V4.01, V4.07, V4.02 , V4.03, V4.04, V4.05, V4.06, V4.07.01, V4.07.02, V4.08, V4.08.01, V4.09, V4.10, V4.11, V4.12, V4.13, V4.14, V4.15, V4.16, V4.16.1, V4.17,  V4.19, V4.20, V4.21, V4.22, V4.23, V4.24, V4.25 , V4.26, V4.27, V4.28, V4.29, V4.30, V4.31, V4.32, V4.33, V4.34, V4.35, V4.m, V4.36, V4.37, V4.37.01, V4.38, V4.38.01, V4.39, V4.40, V4.41, V4.41.01, V4.42, V4.43, V4.44, V4.44.01, V4.45, V4.46, V4.47, V4.48, V4.48.01, V4.49, V4.49.01, V4.49.02, V4.50, V4.50.01, V4.51, V4.52, V4.52.01, V4.53, V4.46.01, V4.54, V4.55, V4.56, V4.57, V4.58, V4.59, V4.60, V4.61, V4.62, V4.63, V4.64, V4.65, V4.66, V4.67.01, V4.68, V4.69, V4.70, V4.71, V4.72, V4.73, V4.74, V4.75, V4.76, V4.77, V4.78, V4.79, V4.79.01, V4.79.02, V4.80, V4.81, V4.81.01, V4.82, V4.83, V4.84, V4.85, V4.86, V4.87, V4.88, V4.89, V4.90, V4.91, V4.93, V4.92, V4.94, V4.95, V4.96, V4.97, V4.96.01, V4.97.01, V4.98, V4.99, V4.100, V5.00, V5.01, V5.02, V5.04, V5.05, V5.06, V5.07, V5.08, V5.09, V5.10, V5.11, V5.12, V5.13, V5.14, V5.15, V5.16, V5.17, V5.18, V5.19, V5.20, V5.21, V5.22, V5.23, V5.24, V5.25, V5.26, V5.27, V5.28, V5.29, V5.30, V5.31, V5.32, V5.33, V5.34, V5.35, V5.36, V5.37, V5.38, V5.39, V5.40, V5.41, V5.42, V5.43, V5.45, V5.46, V5.47, V5.49, V5.50]

The ETag `b2d8515935b063fac31d9494a2f0475f` is also the most recently one but there is no V5.51. After I removed the milestone's ETag from the cache, the update's log is this:

* 25369 29 Aug 2015 16:36:23 INFO UpdateService [pool-4-thread-4] - New ETag for teammates/repo/milestones: Optional[b2d8515935b063fac31d9494a2f0475f]
* 25375 29 Aug 2015 16:36:23 INFO UpdateMilestonesTask [pool-4-thread-4] - teammates/repo | 172 milestone(s)) changed: [V1.0, V2.0, V3.0, V4.1,V4.2, V4.01, V4.07, V4.02 , V4.03, V4.04, V4.05, V4.06, V4.07.01, V4.07.02, V4.08, V4.08.01, V4.09, V4.10, V4.11, V4.12, V4.13, V4.14, V4.15, V4.16, V4.16.1, V4.17,  V4.19, V4.20, V4.21, V4.22, V4.23, V4.24, V4.25 , V4.26, V4.27, V4.28, V4.29, V4.30, V4.31, V4.32, V4.33, V4.34, V4.35, V4.m, V4.36, V4.37, V4.37.01, V4.38, V4.38.01, V4.39, V4.40, V4.41, V4.41.01, V4.42, V4.43, V4.44, V4.44.01, V4.45, V4.46, V4.47, V4.48, V4.48.01, V4.49, V4.49.01, V4.49.02, V4.50, V4.50.01, V4.51, V4.52, V4.52.01, V4.53, V4.46.01, V4.54, V4.55, V4.56, V4.57, V4.58, V4.59, V4.60, V4.61, V4.62, V4.63, V4.64, V4.65, V4.66, V4.67.01, V4.68, V4.69, V4.70, V4.71, V4.72, V4.73, V4.74, V4.75, V4.76, V4.77, V4.78, V4.79, V4.79.01, V4.79.02, V4.80, V4.81, V4.81.01, V4.82, V4.83, V4.84, V4.85, V4.86, V4.87, V4.88, V4.89, V4.90, V4.91, V4.93, V4.92, V4.94, V4.95, V4.96, V4.97, V4.96.01, V4.97.01, V4.98, V4.99, V4.100, V5.00, V5.01, V5.02, V5.04, V5.05, V5.06, V5.07, V5.08, V5.09, V5.10, V5.11, V5.12, V5.13, V5.14, V5.15, V5.16, V5.17, V5.18, V5.19, V5.20, V5.21, V5.22, V5.23, V5.24, V5.25, V5.26, V5.27, V5.28, V5.29, V5.30, V5.31, V5.32, V5.33, V5.34, V5.35, V5.36, V5.37, V5.38, V5.39, V5.40, V5.41, V5.42, V5.43, V5.45, V5.46, V5.47, V5.49, V5.50, V5.51]

Which also has the same Etag `b2d8515935b063fac31d9494a2f0475f` but now has V5.51. So I think the problem can only happen downwards from `GitHubRepo.getUpdatedResource`

**Comment by ndt93** [comment] 2015-09-01 12:56
Seems like there might be problem with our interaction with Github API, especially the ETag with respect to Pagination. Only teammates actually has multiple paged response for milestones list.

So I was manually requesting Github API for teammates API using Postman, and the response has different ETag for the current list of milestones. I also tried to make a request together with the ETag that HubTurbo currently stores for teammates (the Etag in the comment above) and also got a `200` and new list of milestones.

At some point of time today, the ETag changed in response to my manual request because someone closed an issue associated with V5.51 in teammates and return a new list of milestones.

During the entire time (including the past few days), HubTurbo still keep the same ETag for teammates and response `304 - Nothing to update`

A possible problem that I identified is that we open a separate `HttpURLConnection` to Github API just to get the milestones list's ETag and then use egit's `PageRequest` to actually get the milestones list. However, the `HttpURLConnection` is only for the first page of the response, hence the ETag is for the first page only , while each response page should has a separate ETag.

My requests:
* First page: https://api.github.com/repos/teammates/repo/milestones?state=all&per_page=100
* Second page: https://api.github.com/repos/teammates/repo/milestones?state=all&per_page=100


All mentioned code are in: `github.update.UpdateService`. Anyone has any idea on this?

**Comment by ndt93** [comment] 2015-09-01 13:02
If the above is indeed the problem, a clean solution might not be trivial since we need to figure out how to combine, store and handle all the pages' ETags together.

**Comment by damithc** [comment] 2015-09-01 13:38
At least it explains why the problem occurs for teammates but not for hubturbo.

**Comment by dariusf** [comment] 2015-09-01 15:49
Nice findings! I (re-)wrote the ETag-related parts but didn't give it this much attention then. Couldn't figure out why certain ETags were different when requested with EGit vs with a request builder; this may explain it.

An idea is to page through and get every ETag every time, then hash all of them and use the result internally to test for updates.

**Comment by ndt93** [comment] 2015-09-01 16:04
Yup, since this is gonna affect a bunch of things and may need a big fix for all the resources, we should discuss how to design a good solution for it tomorrow.

**Comment by ndt93** [comment] 2015-09-01 16:18
A problem with hashing the whole thing together is that later we still need each ETag to get the actual updated content and I'm not sure if egit's `PageRequest` supports inserting an ETag for each page, otherwise we have to implement the thing ourselves, which is quite bad :|

**Closed** 2015-09-06 13:48 UTC
Labels: feature-milestones, priority.high, type.bug
