### ISSUE TITLE
'Selected' color lost at the end of a sync

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#505] opened 2015-03-08 12:49 UTC
During a sync, the selected issue loses its dark blue color
![image](https://cloud.githubusercontent.com/assets/1673303/6545811/91ca1fb8-c5d4-11e4-8265-20a7ec5204b7.png)

**Comment by damithc** [comment] 2015-03-27 04:54
This happens quite frequently.

**Comment by dariusf** [comment] 2015-06-05 08:40
Duplicate of #647

**Closed by dariusf** 2015-06-05 08:40 UTC
Labels: aspect-sync, priority.high, status.accepted, type.bug
